### PR TITLE
update KanColleHelpers API

### PR DESCRIPTION
**Pull request by Javran**
Related: #461 #589 #594
new APIs are added to deal with combined fleet data:

* `analyzeRawSurfaceTaskForceBattleJS` for dealing with surface task force.

```javascript
> var PS = require( "./KanColleHelpersN" );
> var DA = PS['KanColle.DamageAnalysis'];
> DA.analyzeRawSurfaceTaskForceBattleJS( svdata.api_data )
{ main: 
   [ null,
     { currentHp: 53 },
     { currentHp: 47 },
     { currentHp: 48 },
     { currentHp: 56 },
     { currentHp: 81 },
     { currentHp: 92 } ],
  escort: 
   [ null,
     { currentHp: 24 },
     { currentHp: 13 },
     { currentHp: 30 },
     { currentHp: 29 },
     { currentHp: 10 },
     { currentHp: 38 } ],
  enemy: 
   [ null,
     { currentHp: -165 },
     { currentHp: -326 },
     { currentHp: -9 },
     { currentHp: -79 },
     { currentHp: -94 },
     { currentHp: -10 } ] }
```

* `analyzeRawCarrierTaskForceBattleJS` for dealing with carrier task force (for both regular battle and air battle)

    The usage is the same as `analyzeRawSurfaceTaskForceBattleJS`:

```javascript
> DA.analyzeRawCarrierTaskForceBattleJS( svdata.api_data )
{ main: 
   [ null,
     { currentHp: 77 },
     { currentHp: 77 },
     { currentHp: 69 },
     { currentHp: 70 },
     { currentHp: 45 },
     { currentHp: 55 } ],
  escort: 
   [ null,
     { currentHp: 37 },
     { currentHp: 31 },
     { currentHp: 44 },
     { currentHp: 82 },
     { currentHp: 43 },
     { currentHp: 39 } ],
  enemy: 
   [ null,
     { currentHp: 96 },
     { currentHp: 70 },
     { currentHp: 58 },
     { currentHp: 66 },
     { currentHp: -18 },
     { currentHp: 40 } ] }

```

* `analyzeRawNightBattleCombinedJS`

    The same as `analyzeRawNightBattleJS`, except that now damage is dealt to escort fleets (element#1~6 are escort ships' HPs) instead of main fleets, this API keeps the old ouput format.

```javascript
> DA.analyzeRawNightBattleCombinedJS( svdata.api_data )
[ null,
  { currentHp: 9 },
  { currentHp: 4 },
  { currentHp: 23 },
  { currentHp: 75 },
  { currentHp: 14 },
  { currentHp: 21 },
  { currentHp: 230 },
  { currentHp: 169 },
  { currentHp: 16 },
  { currentHp: -17 },
  { currentHp: 0 },
  { currentHp: 0 } ]
```

This PR is just an API update, for now I don't know how to integrate it with existing code nor could I verify the change (as atm I've not yet got started doing the event). Can someone take over the remaining task?

### CODE REVIEW

**Comment by bamboo3250** [comment]
:+1: can't wait for this get merged. Since I integrated your API with the single fleet, I will do it for combined fleet as well. Only after @dragonjet merged this though :laughing:

**Comment by Javran** [comment]
@bamboo3250 thanks xD

**Comment by bamboo3250** [comment]
@Javran I just tested your API in my fork. It seems there is still sth wrong with the `api_kouku`.

Damage Calculation
screen shot 2015-08-13 at 3 52 16 am

HP from server (expected result)
screen shot 2015-08-13 at 3 52 28 am

Here is the battle data (Air exchange battle) http://pastebin.com/HNDvtF6E

**Comment by Javran** [comment]
@bamboo3250 you are right, I messed up main / escort fleets. Fixed!

**Comment by bamboo3250** [comment]
I just tested on 2 runs in E3. No error detected so far. Well done @Javran :+1:

**Comment by Javran** [comment]
@bamboo3250 :) if possible you can try with support fleets, although I don't have data for testing, that should also work fine.

**Comment by NicolaosGreene** [comment]
Here's my data from my encounter with E-2 Boss with a support fleet
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_deck_id":"1","api_ship_ke":[-1,602,557,595,594,623,623],"api_ship_lv":[-1,1,1,1,1,1,1],"api_nowhps":[-1,81,83,57,41,42,58,270,400,88,80,46,46],"api_maxhps":[-1,92,90,57,57,58,58,270,400,88,80,46,46],"api_nowhps_combined":[-1,29,33,53,52,42,32],"api_maxhps_combined":[-1,32,36,53,52,42,32],"api_midnight_flag":1,"api_eSlot":[[506,506,529,525,-1],[509,509,512,529,-1],[505,505,515,525,-1],[505,505,515,525,-1],[502,559,544,-1,-1],[502,559,544,-1,-1]],"api_eKyouka":[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],"api_fParam":[[102,0,90,92],[99,0,99,98],[77,79,69,75],[77,79,69,75],[34,0,72,65],[34,0,72,65]],"api_eParam":[[69,98,60,170],[180,0,80,160],[79,74,79,89],[73,66,72,82],[58,76,48,36],[58,76,48,36]],"api_fParam_combined":[[48,79,49,49],[59,99,59,59],[77,75,64,72],[78,77,65,72],[69,89,69,69],[59,89,59,59]],"api_search":[1,1],"api_formation":["14",1,1],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[5,6],[-1]],"api_stage1":{"api_f_count":72,"api_f_lostcount":0,"api_e_count":0,"api_e_lostcount":0,"api_disp_seiku":1,"api_touch_plane":[94,-1]},"api_stage2":{"api_f_count":72,"api_f_lostcount":11,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_frai_flag":[-1,0,0,0,0,0,0],"api_erai_flag":[-1,0,1,0,1,0,1],"api_fbak_flag":[-1,0,0,0,0,0,0],"api_ebak_flag":[-1,0,0,1,0,1,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,0],"api_edam":[-1,0,8,0,79.1,16,0]},"api_stage3_combined":{"api_frai_flag":[-1,0,0,0,0,0,0],"api_fbak_flag":[-1,0,0,0,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,0]}},"api_support_flag":2,"api_support_info":{"api_support_airatack":null,"api_support_hourai":{"api_deck_id":4,"api_ship_id":[327,355,350,372,18,3],"api_undressing_flag":[0,0,0,0,0,0],"api_cl_list":[-1,2,0,0,0,0,0],"api_damage":[-1,85,0,0,0,0,0]}},"api_opening_flag":0,"api_opening_atack":null,"api_hourai_flag":[1,1,1,1],"api_hougeki1":{"api_at_list":[-1,1,8,2,7,4,10,3,9,6,12,11],"api_at_type":[-1,6,0,6,0,0,0,0,0,0,0,0],"api_df_list":[-1,[7],[5],[8],[3],[7],[1],[11],[5],[9],[5],[6]],"api_si_list":[-1,[59,137,137],[509],[59,105,105],[506],[90],[505],[90],[505],[-1],[502],[502]],"api_cl_list":[-1,[2],[0],[1],[1],[0],[1],[0],[1],[0],[0],[1]],"api_damage":[-1,[180],[0],[54],[3],[0],[7],[0],[33],[0],[0],[5]]},"api_hougeki2":{"api_at_list":[-1,1,7,2,8,3,9,4,10,6],"api_at_type":[-1,6,0,6,0,0,0,0,0,0],"api_df_list":[-1,[12],[5],[11],[2],[10],[1],[10],[4],[10]],"api_si_list":[-1,[59,137,137],[506],[59,105,105],[512],[90],[505],[90],[505],[-1]],"api_cl_list":[-1,[1],[1],[1],[1],[0],[2],[0],[2],[0]],"api_damage":[-1,[155],[1],[158],[67],[0],[55],[0],[3],[0]]},"api_hougeki3":{"api_at_list":[-1,4,8,3,7,5,9,2,6,1],"api_at_type":[-1,2,0,2,0,2,0,0,0,0],"api_df_list":[-1,[10,10],[6],[8,8],[1],[9,9],[1],[9],[8],[8]],"api_si_list":[-1,[90,90],[509],[90,90],[506],[90,90],[505],[122],[-1],[122]],"api_cl_list":[-1,[1,1],[1],[1,1],[0],[1,1],[1],[0],[1],[1]],"api_damage":[-1,[21,37],[22],[39,27],[0],[6,10],[21],[0.1],[24],[28]]},"api_raigeki":{"api_frai":[-1,0,3,2,1,3,0],"api_erai":[-1,0,0,6,0,0,0],"api_fdam":[-1,0,0,0,0,0,7],"api_edam":[-1,0,28,8.1,0,0,0],"api_fydam":[-1,0,6,28,0,2,0],"api_eydam":[-1,0,0,7,0,0,0],"api_fcl":[-1,0,1,1,1,1,0],"api_ecl":[-1,0,0,1,0,0,0]}}}

**Comment by Javran** [comment]
@NicolaosGreene Thanks for the data, I forgot to accumulate damage dealt by support fleet, now it's fixed (I'll add your data into my testcase if you don't mind)

**Comment by NicolaosGreene** [comment]
It's no problem, that's why I provided the data

**Comment by Javran** [comment]
@NicolaosGreene thanks :)

**Comment by NicolaosGreene** [comment]
E-2 was surprisingly kind so I have only that one data point for now. I've only ended up sorting 9 times so far, despite selecting hard and now clearing through E-2

**Pull request merged**
