### PR TITLE
fix code

### PR DESCRIPTION
**Pull request by McDohl**
it was !== :P 
https://github.com/dragonjet/KC3Kai/commit/0a304544aed05e578ac45f936483bea0bbd958c0

### CODE REVIEW

**Comment by nicky008** [comment]
:notes:

**Comment by McDohl** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by dragonjet** [comment]
oh wait, can Javascript `undefined` safe compare to natural undefined? xD

I haven't actually tested this yet, but I used `!==` for strict compare to check if both variables are either not of the same value, or also of different data type

**Comment by McDohl** [comment]
i tested !== and the quest translation not working. changed to != and its working for now

**Comment by dragonjet** [comment]
ah I see! toplel, it should've been `QuestData.meta().available`. I also forgot it should have `typeof`, tbh I did not test it in-game earlier :3

**Comment by McDohl** [comment]
so its like this? 

if(typeof QuestData.meta().available !== undefined ){

tried and its work.

**Comment by dragonjet** [comment]
yea I didn't know why I was out of mind earlier, must be spacing out :laughing:

**Pull request merged**
