### PR TITLE
[Translation] Change HQ rank translation in Vietnamese

### PR DESCRIPTION
**Pull request by bamboo3250**
@dragonjet is it still possible to include this commit in v15?

### CODE REVIEW

**Comment by dragonjet** [comment]
oops, I wasn't able to check github before I published.

seems there's conflict with `clearBattleData()`, I fixed it on latest.
maybe you can separate the translations so we can pull only that, if it's even possible XD

**Comment by bamboo3250** [comment]
@dragonjet sure, 1 minute. :grin:

**Comment by bamboo3250** [comment]
@dragonjet done

**Comment by dragonjet** [comment]
aye thanx :+1:

**Pull request merged**
