### PR TITLE
[Feature #157] [v10] Dashboard: Vertical (Normal Mode)

### PR DESCRIPTION
**Pull request by bamboo3250**
Solved #157

@dragonjet Here is the Normal Mode for Vertical Layout. Just tell me if you want any amendment. :smile: 

untitled

### CODE REVIEW

**Comment by dragonjet** [comment]
wow that's very fast! and it looks great! just wow, done better than i could have

**Comment by bamboo3250** [comment]
Haha thanks :grin: To prevent conflict, for now I will focus on completing Vertical Layout first. After that I'll take a look at existing issues related to the panel (both orientation).

**Comment by SmokeyTheButt** [comment]
So when I go into battle mode on the vertical layout, I get this odd cutoff. 

audioclip-1434123331

**Comment by bamboo3250** [comment]
I haven't done Battle Mode for Vertical Layout yet so it's expected. I'm going to work on it today. Thanks for reporting.

**Comment by SmokeyTheButt** [comment]
Ah okay.

**Pull request merged**
