### PR TITLE
ExpeditionHelper quick fix

### PR DESCRIPTION
**Pull request by Javran**
A quick fix to make it work with new API, keep in mind that this messes up the current layout a little bit.

### CODE REVIEW

**Comment by bamboo3250** [comment]
Could you take a screenshot while we wait for dragonjet to merge it?

**Comment by Javran** [comment]
Here you go, this is the horizonal one:

2015-07-18_004330_3840x1080_scrot

And vertical one:

2015-07-18_004425_3840x1080_scrot

Basically I just `JSON.stringify` stuff, not really know the best position to place it.

**Comment by bamboo3250** [comment]
That's good. We can temporarily put it inside the white box below. You can leave it to someone else to handle it properly later :+1:

**Comment by Javran** [comment]
I see, thanks xD

**Comment by dragonjet** [comment]
ah I've also put invisible `div`s on that white box so that it will interchange between equipment crafting and expedition helper, that white box was also meant for this xD

dw I'll do the horizotal box for it~

**Pull request merged**
