### PR TITLE
[Fix] Compass result for enemy fleet doesn't work

### PR DESCRIPTION
**Pull request by bamboo3250**
I noticed after moving the Abyssal images to photobucket, the compass cannot show the enemy fleet image anymore so I made a fix for it. Now it looks like this.

untitled

### CODE REVIEW

**Comment by dragonjet** [comment]
looks great :thumbsup:

**Comment by bamboo3250** [comment]
I think so, that __background:rgba(255,255,255,.7);__ was from the enemyFleet previously then I moved it to __transparent-container__.

**Comment by Crazyteitoku** [comment]
@bamboo3250 :+1: on the fix - I was sort of going to remind dragonjet via a thread about a new kc3 kai layout on [wikia](http://kancolle.wikia.com/wiki/Thread:273592#4)

Looks like we can wave bye to the old layout and say hello to the new:

**Comment by bamboo3250** [comment]
I think there is no file named 'library/managers/TimerManager.js' at the moment. Maybe @dragonjet will add this later? Have any idea?

**Comment by dragonjet** [comment]
whoops! fixed it on new commit

**Comment by Crazyteitoku** [comment]
Thanks! latest commit did address the issue.

**Pull request merged**
