### PR TITLE
[Translation]Korean Translation Enhanced

### PR DESCRIPTION
**Pull request by Yukinyaa**
Added Quests.
Updated terms.
Added myself to devs :D

### CODE REVIEW

**Comment by Yukinyaa** [comment]
I'm dumb as hell

**Comment by Yukinyaa** [comment]
Ok, there we go..

**Comment by Yukinyaa** [comment]
If there is any problem please, let me know

**Comment by rephira** [comment]
I feel like a lazy bum now. D= Was working on it without committing because I was thinking about uploading the final version after I finished everything. Oh well.

**Pull request merged**
