### PR TITLE
[Feature] Tracking abyssal Carrier, Transport Ship and Submarine hunt quests

### LINKED ISSUE #325: Use battle results in quest tracking
I assume you are using enemy fleet composition prediction for quest tracking, and I haven't looked at the source code so might be wrong.

I notice after the enemy composition being removed from server response, quests related to sinking ships no longer get tracked, I know it is possible to "replay" the battle by learning `/kcsapi/api_req_sortie/battle`, is it also possible to use it for tracking quest progress?

### PR DESCRIPTION
**Pull request by bamboo3250**
resolved #325

### CODE REVIEW

**Comment by bamboo3250** [comment]
Could anyone, who haven't finished hunting daily quests yet, test this one for me?

**Comment by McDohl** [comment]
is it only for daily? my weekly transport not done yet :sob:

**Comment by bamboo3250** [comment]
it's for all hunting quests, including one time, daily and weekly (we don't have monthly hunting quest) xD

**Comment by bamboo3250** [comment]
I just fixed a bug. Please pull again xD

**Comment by McDohl** [comment]
done, for transport its counting so far. still stuck at daily boss world 2. so cant tell bout submarine. and I'm done with 20CV quest. :(

**Comment by bamboo3250** [comment]
Thanks. If it works with Transport ship, it's likely to work well with other types (unless I mistyped the enemy ids or quest ids xD)

**Comment by ReiFan49** [comment]
if i remember that KC3Master.ship has abyssal data too (ID>500), and it keeps it's class (api_stype),
by checking which api_stype, it could give required enemy type though

also, don't forget that combined fleet may apply. (7-12 may fail, on that case reverse iterate or something)

image

**Comment by bamboo3250** [comment]
Thanks for pointing it out. I never checked KC3Master before.

Regarding combined fleet, we may have to wait for the next event to come so that we can examine the API and update the Damage Calculator (fortunately the Summer event will come soon).

For now, I'll fix to use KC3Master for checking the enemy ship types.

**Pull request merged**
