### PR TITLE
[Fix #435] Quest Translation

### LINKED ISSUE #435: Quest Translation
image
Correct me if I'm wrong, but shouldn't the language used for quest translation match the global language chosen in the settings panel?  I am getting Vietnamese translations while I have English selected.  Is this a side effect of commit e073fa0fa46c03485d75e3dd1392731236c80e56?

### PR DESCRIPTION
**Pull request by bamboo3250**
Fix #435
Reversed quest translation of English
Copied translation to Vietnamese

### CODE REVIEW

**Comment by Crazyteitoku** [comment]
@bamboo3250 lal Erupi pointed out this as an issue in the latest git release.

I'll merge this pull request. Hopefully @dragonjet won't mind. :sweat:

**Comment by bamboo3250** [comment]
It's kinda urgent fix so ... it's my fault, anyway :sweat_smile:

**Comment by Crazyteitoku** [comment]
True but with all that said and done I am not sure if I were granted rights to do merges. I know my main role was to really write up documentation though hopefully @dragonjet won't bite. :sweat_smile:

**Comment by dragonjet** [comment]
rawr :v

**Comment by Crazyteitoku** [comment]
やっぱり (As I thought) … :sweat: waited for @dragonjet to come online somewhere and wanted to apologise lal. Well now, he came and he saw.

**Comment by bamboo3250** [comment]
Haha I feel so bad right now, will discipline myself for this incident. Sorry @Crazyteitoku for making you involved :sweat_smile:

**Comment by Crazyteitoku** [comment]
No, really it is my fault lel. Not yours, dunno if @dragonjet reaction was serious or not. You did a good job in pushing a patch quickly - I just merged the request so that testers like Erupi won't be making bug reports. :+1:

**Comment by bamboo3250** [comment]
Tbh, if I were you, I also would do the same. I were so worried that this issue would cause trouble for other developers after they pulled the most recent commit because most of us still use English when using KC3Kai. The longer it gets merged, the more developers are affected. I am thankful that you merged it soon and kept the number of affected people by my mistake as low as possible. :+1:

**Comment by Erupi** [comment]
Well I want to say sorry for not making the early report because I was somewhat in a hurry when I found out that EN quest translate turned to viet o3o. So I had to ask CT to revert the changes since it might affect others that use devs build and making another 2-3 same issue in git.
CT did a quick job on reverting the change so part of the fault lies on me o3o.

**Comment by dragonjet** [comment]
nah. I'm alright with it @Crazyteitoku 
I even trust everyone enough here to not review codes being pulled :3

**Comment by bamboo3250** [comment]
No, we should do review each other's pull request to prevent this happen again :joy:

**Pull request merged**
