### PR TITLE
Damage calculation

### PR DESCRIPTION
**Pull request by Javran**
Related to #325.

I've implemented damage calculation, you can use 2 functions to get access to this functionality:

* `analyzeRawBattleJS` for regular battles

```javascript
// > PS["KanColle.DamageAnalysis"].analyzeRawBattleJS(svdata.api_data)
[ null,
  { aerial: 0,
    opening: 0,
    hougeki1: 0,
    hougeki2: 0,
    hougeki3: 0,
    closing: 0,
    currentHp: 44 },
  { aerial: 0,
    opening: 0,
    hougeki1: 0,
    hougeki2: 0,
    hougeki3: 0,
    closing: 0,
    currentHp: 39 },
  { aerial: 0,
    opening: 0,
    hougeki1: 4,
    hougeki2: 0,
    hougeki3: 0,
    closing: 0,
    currentHp: 34 },
  { aerial: 0,
    opening: 0,
    hougeki1: 0,
    hougeki2: 0,
    hougeki3: 0,
    closing: 0,
    currentHp: 43 },
  { aerial: 0,
    opening: 0,
    hougeki1: 0,
    hougeki2: 0,
    hougeki3: 0,
    closing: 0,
    currentHp: 90 },
  { aerial: 0,
    opening: 0,
    hougeki1: 0,
    hougeki2: 0,
    hougeki3: 0,
    closing: 0,
    currentHp: 66 },
  { aerial: 0,
    opening: 0,
    hougeki1: 30,
    hougeki2: 48,
    hougeki3: 0,
    closing: 0,
    currentHp: -33 },
  { aerial: 0,
    opening: 0,
    hougeki1: 9,
    hougeki2: 36,
    hougeki3: 0,
    closing: 95,
    currentHp: -80 },
  { aerial: 0,
    opening: 26,
    hougeki1: 7,
    hougeki2: 18,
    hougeki3: 0,
    closing: 25,
    currentHp: 9 },
  null,
  null,
  null ]
```

* `analyzeRawNightBattleJS` for night battles

```javascript
// > PS["KanColle.DamageAnalysis"].analyzeRawNightBattleJS(svdata.api_data)
[ null,
  { hougeki: 0, currentHp: 44 },
  { hougeki: 0, currentHp: 39 },
  { hougeki: 0, currentHp: 34 },
  { hougeki: 0, currentHp: 43 },
  { hougeki: 0, currentHp: 90 },
  { hougeki: 0, currentHp: 66 },
  { hougeki: 0, currentHp: 0 },
  { hougeki: 0, currentHp: 0 },
  { hougeki: 263, currentHp: -254 },
  null,
  null,
  null ]
```

For both functions, the result value is always an array of 13 elements, in which the first element is always `null`. Our ships are indexed `1~6` and enemies `7~12`, a `null` indicates there is no ship in that position. `currentHp` is always returned in both functions, indicating how many HP are remained after the battle is finished, ship with `currentHp <= 0` are sunk. Other fields are damage took in each stage of the battle, should be straightforward. I just tried them for my daily exercises, and the calculation seems to be correct.

To get access to these two functions:

```javascript
var PS = window.PS;
var DA = PS["KanColle.DamageAnalysis"];
// for regular battles
DA.analyzeRawBattleJS(svdata.api_data)
// for night battles
DA.analyzeRawNightBattleJS(svdata.api_data)
```
I assume the input data structured in the same way `svdata.api_data` from server does.

Also a wrong condition for Expedition#38 is fixed.

Please let me know if you are interested in any other information about battles :)

### CODE REVIEW

**Comment by McDohl** [comment]
do you mind to check expedition 35? there's report where it's not working properly 
http://kancolle.wikia.com/wiki/User_blog:Dragonjet/KC3%E6%94%B9#comm-288802

**Comment by Javran** [comment]
@McDohl yes, it was a mistake, fixed in [this commit](https://github.com/Javran/purescript-kancolle-helpers/commit/47087adc12a80f95b3e64af8ce3683fe3dfdb92d). The change is also included in this PR.

**Comment by McDohl** [comment]
thanks for the fast reply :+1:

**Comment by dragonjet** [comment]
nice, excited to see this :+1:

**Comment by bamboo3250** [comment]
I have been waiting for this :+1:

**Comment by Javran** [comment]
@dragonjet @bamboo3250 @McDohl I'm wondering if you guys are using fields other than `currentHp`? I'm doing some refactoring and don't think they are useful for now.
Would it break your code if I remove them in my next version?

**Comment by bamboo3250** [comment]
For now, I only use `currentHp` so it should not have any problem.

**Comment by dragonjet** [comment]
right now I haven't used it, so I'm fine with any

**Pull request merged**
