### PR TITLE
zhCN update and fix for #510

### PR DESCRIPTION
**Pull request by Diablohu**
details on fix for #510

added a check for chrome.cookies for both `Play via API Link` and `Refresh API Link` function

### CODE REVIEW

**Comment by ReiFan49** [comment]
ah i see... (sounds like chrome keeps silent updating huh ....)

**Comment by Crazyteitoku** [comment]
build/tmp/pages/popup/popup.js:

41 |                go_play_via_api()
                                         ^ Missing semicolon.
65 |                go_refresh_api()
                                         ^ Missing semicolon.

2 errors in 64 files

**Comment by Diablohu** [comment]
semicolons added

**Comment by Crazyteitoku** [comment]
Ah I was waiting for the report from Travis CI and now it shows up as checks have passed. :+1: Not really allowed to do merges, etc so I'll let @dragonjet handle it.

**Comment by ethrundr** [comment]
ah those semicolons.....
so it's why I'm seeing the failed test from Travis before :laughing:

**Comment by dragonjet** [comment]
wait, I think this is a matter of permissions.

I'm checking the [chrome API](https://developer.chrome.com/extensions/cookies) and there's no notice of removal on any channel.

will merge this though and edit later, since I forgot that "Play via DMM" also has a middleman page, so the `cookies.set` should be on the `\src\pages\game\web.js` not on `popup.js` :laughing:

**Pull request merged**
