### PR TITLE
[kr]Added Event Quests

### PR DESCRIPTION
**Pull request by Yukinyaa**

### CODE REVIEW

**Comment by Yukinyaa** [comment]
Is it me, or the original soruce

**Comment by ReiFan49** [comment]
nah, i get it why @dragonjet says "Travis-kun" too,

**Comment by dragonjet** [comment]
yep, this too needs a travis-kun :laughing:

**Comment by Crazyteitoku** [comment]
build/tmp/library/objects/Gear.js
     53 |                var veteranPower = (this.ace==7?8:0) * Math.sqrt( this.master().api_tyku )
                                                                                                   ^ Missing semicolon.
    build/tmp/pages/strategy/tabs/aircraft/aircraft.js
    166 |                        ThisCapacity = ThisPlane.MyHolder().slots[ this._slotNums["s"+ThisPlane.itemId] ]
                                                                                                                  ^ Missing semicolon.

**Comment by ReiFan49** [comment]
even the readme says [build|error]
happened at 90e0f4c5f91497a6b7e841fc0f5960b75e38385e

**Pull request merged**
